# Generated by Django 4.1.6 on 2023-02-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчёта')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название интервала')),
                ('period', models.CharField(choices=[('YEAR', 'Год'), ('QRTR', 'Квартал'), ('MNTH', 'Месяц'), ('DTS', 'Конкр. даты')], default='QRTR', max_length=4, verbose_name='Единица измерения')),
                ('interval_type', models.CharField(choices=[('GRWNGA', 'Нарастающим (с открытия)'), ('GRWNG', 'Нарастающим (за период)'), ('SNGL', 'За выбранный'), ('DTS', 'Конкр. даты')], default='SNGL', max_length=6, verbose_name='Тип интервала')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='reports.reporttemplate', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Временой интервал',
                'verbose_name_plural': 'Временые интервалы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Тег')),
                ('tag_type', models.CharField(choices=[('PRGM', 'Для программ'), ('GRP', 'Для групп'), ('VNT', 'Для мероприятий'), ('ALL', 'Для всех')], default='ALL', max_length=4, verbose_name='Тип тега')),
                ('event', models.ManyToManyField(blank=True, related_name='tags', to='datacenter.event', verbose_name='Мероприятия')),
                ('group', models.ManyToManyField(blank=True, related_name='tags', to='datacenter.group', verbose_name='Группы')),
                ('programs', models.ManyToManyField(blank=True, related_name='tags', to='datacenter.educationprogram', verbose_name='Программы')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=15, verbose_name='Номер пункта')),
                ('name', models.CharField(max_length=500, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('PPL', 'Человек'), ('PRGM', 'Программ'), ('VNTS', 'Мероприятий')], default='PPL', max_length=4, verbose_name='Единица измерения')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.reporttemplate', verbose_name='Отчёт')),
                ('stop_tags', models.ManyToManyField(blank=True, related_name='stop_fields', to='reports.tag', verbose_name='Стоп-теги')),
                ('tags', models.ManyToManyField(blank=True, related_name='fields', to='reports.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
    ]
